# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.3
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: allisonbailey95@gmail.com
author_name: AllisonBaileyR14
contract_name: AlgorandApp
preset_name: starter
project_name: algorand

